- hosts: master
  become: yes
  gather_facts: false
  tasks:
    - name: Getting Join Command
      shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: Setting Join 
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"


- hosts: workers
  become: yes
  tasks:
    - name: Joining Cluster
      shell: "{{ hostvars['master'].join_command }} >> node_joined.txt"
      args:
        chdir: $HOME
        creates: node_joined.txt
